### ISSUE TITLE
[Feature request] Auto switch theme depending on the device theme setting

### ISSUE THREAD

**Issue by jfgoncalves** [WDaan/VueTorrent#794] opened 2023-05-02 15:42 UTC
Hi, thank you for making this project, it is a great upgrade from the default web interface.

Could you add a setting, or a 3rd theme button that will use the device’s/OS theme to switch it automatically? So if my device goes into dark mode, VueTorrent would detect that and switch to its own dark mode.

For example, the MDN website has a little button on top with “OS default” as an option.

Thanks

**Comment by Larsluph** [comment] 2023-05-02 22:09
Duplicate of #606

**Closed** 2023-05-03 04:34 UTC
