### ISSUE TITLE
Copy Name, Hash and Magnet does nothing

### ISSUE THREAD

**Issue by InfiniteX95** [WDaan/VueTorrent#492] opened 2022-09-10 15:47 UTC
Right clicking on a torrent and selecting Copy > Magnet, Hash or Name does not copy the magnet link, hash or name as intended.
I'm using v0.18.1 (latest)

**Comment by WDaan** [comment] 2022-09-13 09:02
Are you using firefox?

**Comment by InfiniteX95** [comment] 2022-09-13 14:57
Yes, however, one of my friend was using Chrome and it didn't work either for him :/

**Comment by Anteus** [comment] 2022-10-02 20:16
I get the "navigator.clipboard is undefined" seems like it could be that Firefox requires a secure context aka served from https for that API to work. Maybe needs some workaround?

**Comment by WDaan** [comment] 2022-10-11 05:40
Just checked with Chrome, Safari and Firefox on the latest version and all seems to work fine 🤔 
(Tested on a macbook on both localhost and domain with SSL)

**Comment by Anteus** [comment] 2022-10-11 07:29
Localhost is probably exempted from that. Maybe you can replicate it with http and your local IP eg http://192.168.x.x instead of localhost.

**Comment by tmknight** [comment] 2022-10-11 11:43
I can confirm this behavior:  When using FQDN, it works as expected.  When I use IP address, nothing is copied.

**Comment by WDaan** [comment] 2022-10-13 05:17
So I guess it depends on the settings of your browser to allow it or not?

Anything we can do on the project side, if not we can close this.

**Comment by tmknight** [comment] 2022-10-13 12:02
I don't believe it is browser specific, it is down to how the VueTorrent "copy" interacts with the host.  I do believe it to require a review  of the coding behind those actions.

@WDaan, have you attempted the very same test using IP address to observe the behavior?

**Comment by WDaan** [comment] 2022-10-16 17:21
Seems like the clipboard api is just not supported when using an inscure host.
I'm not sure if there's a workaround for this.

Any reason you can't use a secure host?

**Comment by tmknight** [comment] 2022-10-16 17:25
For me, no big deal; I don't use this feature as a general rule.  I was only trying to help shed light and provide details additional to the OP.

If it's down to SSL vs non-SSL as the "root cause", I suggest this issue be closed as WAD

**Closed** 2022-10-19 05:20 UTC
