### ISSUE TITLE
Torrent data is not visible on mobile

### ISSUE THREAD

**Issue by Antonio36996** [WDaan/VueTorrent#745] opened 2023-03-29 22:24 UTC
When I hold down to access the dropdown menu it interacts as it should, but all the torrent data is not showing.
Works well on computer and tablet, and also if I enable the desktop view on chrome.
I'm using the latest version (1.5.3), it started happening suddenly on 1.5.2, updated to the new version but stills the same
Also tried old versions with same result
Also tried decreasing the number of torrents showed per page and same result
Also tried deleting torrents just in case it wasn't able to load that amount 
Also tried from the computer changing the dpi just in case it was a problem from the phone, but it shows the same empty page.
Also tried cleaning all the browser data, all the vuetorrent folder, and nothing changes.

¡Thanks in advance!

![Screenshot_2023-03-29-23-57-25-133_com android chrome](https://user-images.githubusercontent.com/66578721/228679440-a6263473-4369-4689-b953-15bb522aee23.jpg)

**Comment by Larsluph** [comment] 2023-03-30 04:27
Duplicate of #723

**Closed** 2023-03-30 05:16 UTC
