### ISSUE TITLE
Register to handle magnet links option is missing

### ISSUE THREAD

**Issue by t9999clint** [WDaan/VueTorrent#781] opened 2023-04-26 23:09 UTC
In the default theme there's an option to associate the webui as the default app for magnet urls. This option is missing from your theme (or I'm blind and I just can't find it).
Also if there's a way to also associate with .torrent files that'd be neat.

**Comment by WDaan** [comment] 2023-04-27 05:11
Duplicate of #631?

**Comment by t9999clint** [comment] 2023-04-27 14:38
just noticed that it's a duplicate of issue #111 
Sorry about that

**Closed** 2023-04-27 16:51 UTC
