### ISSUE TITLE
Add default theme toggle

### ISSUE THREAD

**Issue by ticklemyIP** [WDaan/VueTorrent#889] opened 2023-06-23 20:12 UTC
Some browsers utilize anti-fingerprinting settings which include blending dark mode users with light mode users by turning dark mode off. On regular websites this is fine but when visiting the WebUI this can be off putting. Turning the WebUI theme on and off is fine until the browser wipes cookies (i assume that's how it works with Vuetorrent), and auto-deleting browsers are unable to save this setting in addition to always having light theme by  default.

I'm asking for a global always on theme toggle that would allow to permanently set the default WebUI theme to dark.

**Comment by Larsluph** [comment] 2023-06-23 22:45
All the data for VueTorrent is stored in the local storage which is clear at the same time as cookies, and unfortunately it's impossible to do because VueTorrent is a client-side app, we can't store anything on the server.
Duplicate of #83

**Closed** 2023-06-24 07:18 UTC
