### ISSUE TITLE
Minimum column width for Chinese in Table mode

### ISSUE THREAD

**Issue by VEWION** [WDaan/VueTorrent#1428] opened 2023-12-25 10:22 UTC
The column width depends on the window width for now so when using Chinese in Table mode all columns become extremely narrow. Is it able to add a minimum width for columns or can even make it like the OG webui which can be adjusted for each column?
Normal window:
![螢幕擷取畫面 2023-12-25 101653](https://github.com/WDaan/VueTorrent/assets/56110451/5cedcaad-6a23-4ec4-9a96-bf7cceb52362)
Wide window:
![螢幕擷取畫面 2023-12-25 101706](https://github.com/WDaan/VueTorrent/assets/56110451/3b7d5dde-d004-419b-9da3-fdc9c8134c31)

**Comment by Larsluph** [comment] 2023-12-25 12:38
The table column width are automatically determined by the browser for now

**Comment by Larsluph** [comment] 2023-12-25 12:39
Duplicate of #1401

**Closed by Larsluph** 2023-12-25 12:39 UTC
