### ISSUE TITLE
No torrent show on mobile UI

### ISSUE THREAD

**Issue by PozoSer** [WDaan/VueTorrent#779] opened 2023-04-25 09:16 UTC
Since a couple of weeks I have had this issue where the mobile UU (Safari in this case) does not show anything. On the pc it works fine.

I've tried rebooting the docker and even the Sever to no avail.

Any ideas?

![image](https://user-images.githubusercontent.com/18380820/234231549-508356b8-0ee2-449c-bfd4-12cf0dae0592.jpeg)

**Comment by Larsluph** [comment] 2023-04-25 10:06
Duplicate of #774

**Comment by PozoSer** [comment] 2023-04-25 10:13
Thanks and sorry for not seeing it.

**Closed** 2023-04-25 10:13 UTC
