### ISSUE TITLE
Search window

### ISSUE THREAD

**Issue by jsmdy** [WDaan/VueTorrent#442] opened 2022-06-14 07:59 UTC
90% of the time i do a research, when I hit Enter it closed the window because the mouse cursor is not on the entry area. 
This is annoying :D. Can it be possible to not consider the "Enter" key as a clic,?  because a clic outside the search window is the way to close the window

**Comment by WDaan** [comment] 2022-06-14 19:38
Duplicate of #259

**Closed** 2022-06-14 19:38 UTC
