### ISSUE TITLE
[Feature request] Compact list view

### ISSUE THREAD

**Issue by jbonet** [WDaan/VueTorrent#988] opened 2023-07-20 09:38 UTC
Hello,

I would like to request this feature. There are times, when you have a lot of torrents, that you just want to see as much as possible.

The compact mode could be a toggle that would convert the list to a list of cards like it's now, but just showing "name" and "status", reducing its height.

This could also be a setting toggle.

**Comment by Larsluph** [comment] 2023-07-20 09:55
Duplicate of #157

**Closed** 2023-07-20 11:51 UTC
