### ISSUE TITLE
Show Info -> Content -> (rename top directory folder) not available [Windows]

### ISSUE THREAD

**Issue by X73RN4L** [WDaan/VueTorrent#354] opened 2021-12-27 16:02 UTC
Top directory folder doesn't show ability to edit folder name. Does show amount of files inside directory along with being able to edit the file names inside of directory.

**Comment by WDaan** [comment] 2021-12-27 20:29
Duplicate of #175?

**Comment by X73RN4L** [comment] 2021-12-27 20:48
You are correct, my mistake

**Closed** 2021-12-27 20:49 UTC
