### ISSUE TITLE
Selecting file before download

### ISSUE THREAD

**Issue by Antoine2tt** [WDaan/VueTorrent#1317] opened 2023-11-16 21:02 UTC
Hi !
First, thanks for VueTorrent ! Amazing ui :) 

If i want only some files in a torrent, i need to ;

Add the torrent
Disable auto download
Right click on torrent -> Show info -> Content 

Let's say it's a show of 10 seasons, where each seasons is a folder, and each folder (season) contains 15 episodes, if i only want 4 episodes from season 4, 

I need to manually go to every folder, and click on each file to disable file downloading 

And then, i need to go back to the home page to start the torrent ! 

Is there maybe a way, or maybe it's already planed to have kind of checkbox on the left of each folder, and then let's say if i uncheck the root folder of a torrent, it disable recurcivly all download ? 

And for exemple, if i uncheck the season 3 checkbox, it disable all the files inside of this folder ? 

Sorry for my english, not my native language  ! 
This is, of course, not a complain, just an idea ^^ 

Have a great day

**Comment by the-mentor** [comment] 2023-11-28 07:08
I'm having the same problem and I think before the migrate to vue3 it wasnt like this.

**Comment by Larsluph** [comment] 2023-12-28 08:58
Duplicate of #1432, closed this one to keep the new issue form

**Closed by Larsluph** 2023-12-28 08:58 UTC
Labels: duplicate, Improvement, Content Tab
