### ISSUE TITLE
Set priority on folders

### ISSUE THREAD

**Issue by papampi** [WDaan/VueTorrent#1348] opened 2023-11-21 13:28 UTC
On default Web ui we can set/change priority of folders.

PLease add it to vue. 

![Screenshot from 2023-11-21 16-56-37](https://github.com/WDaan/VueTorrent/assets/1108483/88527bcd-0cee-4573-b464-dca61380d7c5)
![Screenshot from 2023-11-21 16-58-00](https://github.com/WDaan/VueTorrent/assets/1108483/608d8c76-3833-4355-b89a-6a7b73001af7)

**Comment by papampi** [comment] 2023-11-21 16:29
It also shows folders completion percentage, would be nice to have that too.

**Comment by Larsluph** [comment] 2023-11-21 16:47
Duplicate of #1019

**Closed by Larsluph** 2023-11-21 16:47 UTC
