### ISSUE TITLE
Hitting the return key when searching causes a page refresh

### ISSUE THREAD

**Issue by Theo-user** [WDaan/VueTorrent#347] opened 2021-12-17 13:15 UTC
With Firefox, after clicking the magnifying glass "Search new torrent", entering a keyword and pressing the keyboard return key, the webui just refreshes instead of searching for the keyword.

**Comment by WDaan** [comment] 2021-12-17 16:10
duplicate of #259?

**Closed** 2021-12-17 20:40 UTC
