### ISSUE TITLE
Download/upload speed broke a few version ago

### ISSUE THREAD

**Issue by SnippetSpace** [WDaan/VueTorrent#790] opened 2023-04-30 23:37 UTC
I use Vuetorrent through the hotio qbittorrent container. For a few versions the downloads and upload card controls have been broken. The settings also reflect this. I tried downloading the skin separately in a new folder but the issue remains. Both the skin and qbittorrent are on the latest public versions. Settings have not been modified from defaults.

Any idea? 

![controls](https://user-images.githubusercontent.com/917744/235381257-0b382f12-831d-4df2-867d-0bda22b06fa1.png)
![sett](https://user-images.githubusercontent.com/917744/235381259-c9c38771-90b6-48b7-9a62-d19c1f2d5db4.png)

**Comment by Larsluph** [comment] 2023-05-01 07:59
Duplicate of #738

**Closed** 2023-05-01 09:38 UTC
